name: CI Checks

on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit hook
        run: |
          pre-commit install -f --install-hooks
          pre-commit run -a -v --color=always --show-diff-on-failure
