SET SERVEROUTPUT ON

DECLARE
    ID  EMP.EID%TYPE:=1;
    SAL EMP.SALARY%TYPE;
    
BEGIN
    SELECT SALARY INTO SAL FROM EMP WHERE EID = ID;
    IF (SAL <= 20000) THEN
        UPDATE EMP SET SALARY=SALARY+2000 WHERE EID = ID;
        DBMS_OUTPUT.PUT_LINE('Salary is updated');
    END IF;
END;
/