set serveroutput on 

CREATE TABLE EMP(EID NUMBER, ENAME VARCHAR2(20), SALARY NUMBER);

INSERT INTO EMP VALUES(1,'Piyush',150);
INSERT INTO EMP VALUES(2,'Shubham',1500);
INSERT INTO EMP VALUES(3,'Jayesh',2500);